from __future__ import annotations

from typing import Any, Iterable, Mapping, Protocol


class TaskRecordRepository(Protocol):
    """Persistence contract used by the project-scoped PostgreSQL TaskStore."""

    def is_initialized(self) -> bool: ...

    def load_all(self) -> list[dict[str, Any]]: ...

    def load_recent(self, limit: int) -> list[dict[str, Any]]: ...

    def load_metrics(self, task_ids: Iterable[str]) -> list[dict[str, Any]]: ...

    def get(self, task_id: str) -> dict[str, Any] | None: ...

    def replace_all(self, records: Iterable[Mapping[str, Any]]) -> None: ...

    def upsert(self, record: Mapping[str, Any]) -> None: ...

    def upsert_many(self, records: Iterable[Mapping[str, Any]]) -> None: ...

    def delete_many(self, task_ids: Iterable[str]) -> int: ...


__all__ = ["TaskRecordRepository"]
